services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    network_mode: host
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    env_file: ./backend/.env
    cap_add:
      - NET_ADMIN
