# Generated by Django 4.2.30 on 2026-06-20 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('public_key', models.CharField(max_length=100, unique=True)),
                ('endpoint', models.CharField(blank=True, max_length=100)),
                ('allowed_ips', models.TextField(blank=True)),
                ('persistent_keepalive', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HandshakeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_handshake', models.DateTimeField(blank=True, null=True)),
                ('rx_bytes', models.BigIntegerField(default=0)),
                ('tx_bytes', models.BigIntegerField(default=0)),
                ('is_reachable', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handshakes', to='servers.server')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['captured_at'], name='servers_han_capture_f82ae2_idx'), models.Index(fields=['server'], name='servers_han_server__27900e_idx')],
            },
        ),
    ]
